### ISSUE TITLE
Support for OctoPrint 1.4.0

### ISSUE THREAD

**Issue by SargonofAssyria** [amsbr/OctoPrint-Stats#36]
Please support for python 3.7 via the new plugin property __plugin_pythoncompat__

**Comment by benjamin-salchow** [comment]
I had the same issue. I created a Pull Request: https://github.com/amsbr/OctoPrint-Stats/pull/37 with informations to run it with python 3.7.

But keep in mind, that you need to install a Raspbian package:

```
apt install libatlas-base-dev
```

You can install it from my repository as zip: https://github.com/benjamin-salchow/OctoPrint-Stats/archive/master.zip

**Comment by SargonofAssyria** [comment]
Tnx, that did it. It's working now.
I put ___plugin_pythoncompat__ = ">=2.7,<4"_ in several other plugins as well.
Pitty that @amsbr does not respond.

**Comment by gvmturl** [comment]
> Tnx, that did it. It's working now.
> I put _**plugin_pythoncompat** = ">=2.7,<4"_ in several other plugins as well.
> Pitty that @amsbr does not respond.

How to do that bro? Still having problems here....



> I had the same issue. I created a Pull Request: #37 with informations to run it with python 3.7.
> 
> But keep in mind, that you need to install a Raspbian package:
> 
> ```
> apt install libatlas-base-dev
> ```
> 
> You can install it from my repository as zip: https://github.com/benjamin-salchow/OctoPrint-Stats/archive/master.zip

Not worked!

Anyhelp for that?

**Comment by benjamin-salchow** [comment]
Just run:
```apt install libatlas-base-dev```

and afterwards remove the plug-in and install it from: https://github.com/benjamin-salchow/OctoPrint-Stats/archive/master.zip 

This contains the `plugin_pythoncompat` and should work. Works on my Python 3 set-up like a charm.

@amsbr could you please take a look at my pull request?

**Comment by gvmturl** [comment]
> Just run:
> `apt install libatlas-base-dev`
> 
> and afterwards remove the plug-in and install it from: https://github.com/benjamin-salchow/OctoPrint-Stats/archive/master.zip
> 
> This contains the `plugin_pythoncompat` and should work. Works on my Python 3 set-up like a charm.
> 
> @amsbr could you please take a look at my pull request?

Thanks for replying!
am i doing something wrong?
1# Access Raspberry by Putty
2# sudo apt install libatlas-base-dev
3# sudo reboot
4# Install plugin using Plugin Manager pasting the link:
https://github.com/benjamin-salchow/OctoPrint-Stats/archive/master.zip

is it correct?
Maybe some broken data made by fails installation making me this troble?

`ERROR: Command errored out with exit status 1:command: /home/pi/oprint/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-o3_Tqk/pandas/setup.py'"'"'; __file__='"'"'/tmp/pip-install-o3_Tqk/pandas/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-o3_Tqk/pandas/pip-egg-infocwd: /tmp/pip-install-o3_Tqk/pandas/Complete output (51 lines):Traceback (most recent call last):File "<string>", line 1, in <module>File "/tmp/pip-install-o3_Tqk/pandas/setup.py", line 746, in <module>**setuptools_kwargs)File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup_install_setup_requires(attrs)File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requiresdist.fetch_build_eggs(dist.setup_requires)File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/dist.py", line 720, in fetch_build_eggsreplace_conflicting=True,File "/home/pi/oprint/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolvereplace_conflicting=replace_conflictingFile "/home/pi/oprint/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_matchreturn self.obtain(req, installer)File "/home/pi/oprint/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtainreturn installer(requirement)File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/dist.py", line 787, in fetch_build_eggreturn cmd.easy_install(req)File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_installreturn self.install_item(spec, dist.location, tmpdir, deps)File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 705, in install_itemdists = self.install_eggs(spec, download, tmpdir)File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggsreturn self.build_and_install(setup_script, setup_base)File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_installself.run_setup(setup_script, setup_base, args)File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setuprun_setup(setup_script, args)File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setupraiseFile "/usr/lib/python2.7/contextlib.py", line 35, in __exit__self.gen.throw(type, value, traceback)File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_contextyieldFile "/usr/lib/python2.7/contextlib.py", line 35, in __exit__self.gen.throw(type, value, traceback)File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modulessaved_exc.resume()File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resumesix.reraise(type, exc, self._tb)File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modulesyield savedFile "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_contextyieldFile "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup_execfile(setup_script, ns)File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfileexec(code, globals, locals)File "/tmp/easy_install-lrjTcj/numpy-1.18.2/setup.py", line 32, in <module>RuntimeError: Python version >= 3.5 required.----------------------------------------ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.Error!Could not parse output from pip, see plugin_pluginmanager_console.log for generated output`


Thank you!!!

**Comment by benjamin-salchow** [comment]
You're welcome. The steps are correct that you wrote. 

By looking at the log it looks like an issue with your installation. Because the log says that you're using "/home/pi/oprint/bin/python2" - but your installation of numpy and panda is for Python version >= 3.5. Try to resetup/reinstall the virtual python environment with Python 3.

Then it should work and in the log should be no "pyhton2" anymore ;-)

**Comment by gvmturl** [comment]
> reinstall the virtual python environment with Python 3

Hello Benjamin! Thank you for replying. I m following these steps below replacing all 3.6.0 by 3.8.2 that seems be the last version of python.


```
wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tgz
tar xzvf Python-3.6.0.tgz
cd Python-3.6.0/
./configure
make -j4
sudo make install

```

not worked... tried using 3.5 version, also tried creating an alias for python and setuping tinydb, pand and numpy by using sudo pip3

What i m doing wrong?

Thank you for your time bro.

**Comment by gvmturl** [comment]
Any help please?
This plugin is so important for what i need.

**Comment by benjamin-salchow** [comment]
Hello,

follow the instructions here: https://github.com/OctoPrint/OctoPrint#installation

Do a reinstall of OctoPrint and use the following commands instead of the shown version in this link I shared:
```sh
virtualenv --python=python3.7 venv
# instead of: virtualenv --python=python2.7 venv
```

Then you move on with the installation and afterwards you add all the plugins to it.

If you do it this way, all will be correct. Use `virtualenv` and not the Python Installation that you wrote 2 days ago. In your system there will be now a mix of Python2 from the system and Python3 that you installed manually on it. If it does not work I would recommend to reinstall the Pi complete. The manual installation could damage system-packages and the repair of it would take even longer than a new installation from scratch.

Hope that helps ;-).

**Comment by gvmturl** [comment]
> Hello,
> 
> follow the instructions here: https://github.com/OctoPrint/OctoPrint#installation
> 
> Do a reinstall of OctoPrint and use the following commands instead of the shown version in this link I shared:
> 
> ```shell
> virtualenv --python=python3.7 venv
> # instead of: virtualenv --python=python2.7 venv
> ```
> 
> Then you move on with the installation and afterwards you add all the plugins to it.
> 
> If you do it this way, all will be correct. Use `virtualenv` and not the Python Installation that you wrote 2 days ago. In your system there will be now a mix of Python2 from the system and Python3 that you installed manually on it. If it does not work I would recommend to reinstall the Pi complete. The manual installation could damage system-packages and the repair of it would take even longer than a new installation from scratch.
> 
> Hope that helps ;-).



Brother, thank you again.
I m really sorry. I m starting everything again.
To start must i download the image and install it with Raspberry Imager, then change values to connect on wifi...?!?

Login to Putty as pi then follow those steps?
Checkout OctoPrint: git clone https://github.com/OctoPrint/OctoPrint.git
Change into the OctoPrint folder: cd OctoPrint
Create a user-owned virtual virtualenv --python=python3.7 venv
Install OctoPrint into that virtual environment: ./venv/bin/pip install 

Not sure if it is... i m getting errors. tried something else

sudo apt update
source venv/bin/activate
pip install pip --upgrade
pip install octoprint

but still have some errors on octoprint installation... Its is installed... but still getting the same problem to install plugin...

Could you try to show me what i m doing wrong please? I dont know what i m doing. I m sorry and thank you again.

**Comment by benjamin-salchow** [comment]
Hello,
try an installation with the standard Raspbian image. If this also not work I'm really not sure what the problem is. Looks like a damaged pyhton2 and python3 setup to me. I'm not using the Octoprint Image, so can't test that.

**Comment by gvmturl** [comment]
> Hello,
> try an installation with the standard Raspbian image. If this also not work I'm really not sure what the problem is. Looks like a damaged pyhton2 and python3 setup to me. I'm not using the Octoprint Image, so can't test that.

Hello man, thank you. Solved the problem by following these steps:
```
pip install --upgrade pip 
git clone https://github.com/foosel/OctoPrint.git
virtualenv --python=python3.7 venv 
cd OctoPrint  
source venv/bin/activate

sudo apt-get install python3-setuptools python3-pyqt5 python3-pip
git checkout devel 
python setup.py clean 
pip install -e .[develop,plugins] 
octoprint serve 

Clear oprint folder that is on pi@octopi then copied all content of venv folder, so octopi image will start on python 3 env
```

Now i having problems with some plugins that are not compatible with python 3, found some on your repository, thank you. But still have some that i d like to use. How can i make then compatible with this version of python? Tried using 2to3 library but didn't work. Are you going to translating more plugins? Some repo seems to be died T_T .

Thank you bro.

**Comment by benjamin-salchow** [comment]
I'm glad that I could help you. Yes, many plug-ins are not maintained any more. All of my "merge" requests are not integrated yet. I did not use the 2to3 library, I just changed the source code. Take a look at my changes I did in the plug-ins. In many it is just that line : `__plugin_pythoncompat__ = ">=2.7,<4"`

E.g. here: https://github.com/amsbr/OctoPrint-Stats/pull/37/commits/81878c03f76020d84df7b39e77f58bc828a19948

See the deltas of my changes and try it for your plug-ins that don't have any python 3 compatibly. Then you have to test it and see in the logs, if there are other errors. That's a pragmatic way to do it - but the fastest. The Python 2 to 3 was started way to late in OctoPrint.. The EOL of Python 2 is well known since years.

**Comment by gvmturl** [comment]
> I'm glad that I could help you. Yes, many plug-ins are not maintained any more. All of my "merge" requests are not integrated yet. I did not use the 2to3 library, I just changed the source code. Take a look at my changes I did in the plug-ins. In many it is just that line : `__plugin_pythoncompat__ = ">=2.7,<4"`
> 
> E.g. here: [81878c0](https://github.com/amsbr/OctoPrint-Stats/commit/81878c03f76020d84df7b39e77f58bc828a19948)
> 
> See the deltas of my changes and try it for your plug-ins that don't have any python 3 compatibly. Then you have to test it and see in the logs, if there are other errors. That's a pragmatic way to do it - but the fastest. The Python 2 to 3 was started way to late in OctoPrint.. The EOL of Python 2 is well known since years.

Hello Benjamin, thank you. worked on the following plugins
OctoPrint-FullScreen
OctoPrint-Autoselect
OctoPrint-Autoscroll
OctoPrint-ExcludeRegionPlugin

How can check the logs?

Where is located the folder with the installed plugins?

Maybe could you take a look on those plugins?
https://github.com/fabianonline/OctoPrint-Telegram
https://github.com/devildant/OctoPrint-ShutdownPrinter


Thank you again!

**Comment by foosel** [comment]
I just came across this why following up on OctoPrint/plugins.octoprint.org#434... To clarify, OctoPrint 1.4.0 does not require Python 3 to function. A dependency of this plugin however does apparently (and it should either be pinned to an older version that still supports Python 2 or this plugin needs to be migrated to Python 3 only and marked accordingly on the repository).

Plugins having Python 3 only dependencies has nothing to do with OctoPrint 1.4.0. I would appreciate it if people would stop spreading this non sense that OctoPrint will only work under Python 3 now, due to issues with third party plugins that have failed to pin their dependencies to versions known to work properly.

**Comment by SargonofAssyria** [comment]
It might work, but read this: https://www.python.org/doc/sunset-python-2/

**Comment by foosel** [comment]
You honestly think I don't know that? I spent the past year doing nothing but prepping OctoPrint 1.4.0 to be Python 3 *and* 2 ready, so that it would be prepared for both people knowing that and people ignoring that.

**Comment by benjamin-salchow** [comment]
Hello @foosel ,
first thank you very much for your great work on OctoPrint. It's really a great software for my 3D printer and I'm glad to use it for all my prints. In addition, a big thank you for maintaining OctoPrint so good.
You're right, my pull request was not tested with Python 2 and regarding the dependencies it won't work anymore with Python 2. 
I run OctoPrint complete with Python 3 so I created many pull request to some plug-ins that didn't utilize Python 3 Support. In most cases this is easily done. In some cases there are dependencies used that require now Python 3, like here with numpy.
This issue is not good, because as you mentioned OctoPrint 1.4.0 runs on Python 2 as Python 3, so the issue is, that this plug-in wasn't Python 3 compatible. I hope the maintainer of this plug-in will shortly take a look at it and change it. But many plug-ins I committed a pull request months ago did not answer or support it in any way but I hope that this could be solved soon. I don't know what the best practice is to utilize Python 2 and Python 3 support, if the dependency requires a dedicated Python version.

**Comment by foosel** [comment]
> I don't know what the best practice is to utilize Python 2 and Python 3 support, if the dependency requires a dedicated Python version.

Version pinning & environment markers/dynamic environment detection. I do that in OctoPrint too, exactly due to the mentioned problem:

https://github.com/OctoPrint/OctoPrint/blob/ef3c8bb6c24f2f94b6c2f486e96c7fe098f06dcd/setup.py#L114-L129

Or alternatively marking the plugin as Python 3 only here and on the repository.

> But many plug-ins I committed a pull request months ago did not answer or support it in any way

I fear the Python 3 switch will reveal quite a number of plugins that are now unmaintained/abandoned by their authors. If you come across stuff like that please use the link to report abandoned plugins on the plugin repository, since that at least will show people the current state of affairs and maybe help in recruiting a new maintainer.
