### ISSUE TITLE
Months showing wrong events.

### ISSUE THREAD

**Issue by arose62** [amsbr/OctoPrint-Stats#8]
I have done only 1 print so far this month, but the graphs are showing large numbers of all events for the current month.
Below are screenshots - the History image shows correctly only 1 job in August.
![history01aug](https://user-images.githubusercontent.com/3906422/28805970-c417eca4-76b0-11e7-9881-3467cc5a08f3.png)
This screenshot shows how Print-Stats has lots and lots of events for August (which is incorrect).
![stats01aug](https://user-images.githubusercontent.com/3906422/28805971-c5dd6514-76b0-11e7-8c5e-ec1c84cf6711.png)

**Comment by gztproject** [comment]
I have the same problem (OctoPrint 1.3.6 running on OctoPi 0.14.0), events from November are showing up in January. It seems the problem is in back-end as the JSON data shows the same as charts.
I attached print history .csv and JSON response in .zip

![slika](https://user-images.githubusercontent.com/8314666/34821327-a1b8fd86-f6c3-11e7-9e22-c47102351cd9.png)

[history.zip](https://github.com/amsbr/OctoPrint-Stats/files/1622221/history.zip)

**Comment by amsbr** [comment]
Hi,

I will prepare a new release in some days.

**Comment by sajovicd** [comment]
I have same problem, in april I made 9 prints, but it is showing 166.
![stats](https://user-images.githubusercontent.com/25117093/38537519-7ae82c10-3c8f-11e8-92f7-abc3983389d7.jpg)

**Comment by gztproject** [comment]
I just submitted a pull request, so far the testing looks great! :)
![screenshot from 2018-09-07 01-52-18](https://user-images.githubusercontent.com/8314666/45190921-afb00680-b240-11e8-95cb-97f892c7d13e.png)

**Comment by amsbr** [comment]
Hi @arose62 @gztproject @sajovicd!

Please try the renewed version, 2.0.0
